sudo: false
language: python
os: linux
jobs:
  include:
    - python: "3.9"
      env: TOXENV=py39
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.10-dev"
      env: TOXENV=py310
  allow_failures:
    - python: "3.10-dev"
      env: TOXENV=py310
before_install:
  # Fix for cryptography on Py36
  - pip install --upgrade virtualenv
install:
  - pip install tox-travis
  - pip install flake8
script:
  - tox
